# Normal Classification
dataset:
  budget: 150
#  budget: 400
  classifier_fitting_mode: from_scratch
  initial_points_per_class: 10
  classifier_batch_size: 32
  validation_split: 0.2

classifier:
  type: MLP
  hidden: [24, 2]

optimizer:
  type: NAdam
  lr: 0.001
  weight_decay: 0.0

