classifier:
  type: MLP
  hidden: [ 24, 12 ]

classifier_embedded:
  type: Linear

pretext_encoder:
  type: MLP
  hidden: [64]
  feature_dim: 48

pretext_optimizer:
  type: NAdam
  lr: 0.000460067792960977
  weight_decay: 1.42285350366666E-05
  lr_scheduler: cosine
  lr_scheduler_decay: 0.000168711268026846

pretext_transforms:
  gauss_scale: 0.168197420127199

pretext_clr_loss:
  temperature: 0.147012543510125

pretext_training:
  batch_size: 431
  epochs: 200
