classifier:
  type: MLP
  hidden: [24, 12]

classifier_embedded:
  type: Linear

pretext_encoder:
  type: MLP
  hidden: [64, 64]
  feature_dim: 24

pretext_optimizer:
  type: NAdam
  lr: 0.000241583061943485
  weight_decay: 6.01796488272691E-06
  lr_scheduler: cosine
  lr_scheduler_decay: 0.000159669730361258

pretext_transforms:
  gauss_scale: 0.213351438270739

pretext_clr_loss:
  temperature: 0.161415045140356

pretext_training:
  batch_size: 169
  epochs: 200
