dataset:
  domain: alarm
  budget: 200
  initial_points_per_class: 1
  classifier_batch_size: 64
  validation_split: 0.2

classifier:
  type: BiLSTM

optimizer:
  type: NAdam
  lr: 0.01
  weight_decay: 0.0

dataset_embedded:
  encoder_checkpoint: "Not supported"
