dataset:
  domain: alarm
  budget: 200
  classifier_fitting_mode: finetuning
  initial_points_per_class: 1
  classifier_batch_size: 64
  validation_split: 0.25

classifier:
  type: BiLSTM
  dropout: 0.05

optimizer:
  type: NAdam
  lr: 0.00155412888113029
  weight_decay: 1.77805840656653E-07

