# Normal Classification
dataset:
  budget: 50
  initial_points_per_class: 1
  classifier_batch_size: 43
  validation_split: 0.2

classifier:
  type: MLP
  hidden: [24, 12]

optimizer:
  type: NAdam
  lr: 0.001
  weight_decay: 0.0
