# Normal Classification
dataset:
  budget: 900
  initial_points_per_class: 1
  classifier_batch_size: 43

classifier:
  type: MLP
  hidden: [24, 12]

optimizer:
  type: NAdam
  lr: 0.001
  weight_decay: 0.0

# Embedded Classification
dataset_embedded:
  encoder_checkpoint: encoder_checkpoints/usps_31.03/model_seed1.pth.tar
  budget: 200
  initial_points_per_class: 1
  classifier_batch_size: 64

classifier_embedded:
  type: MLP
  hidden: [48]

optimizer_embedded:
  type: Adam
  lr: 0.00598186412371846
  weight_decay: 5.4369039633796E-07

# Pretext Task (SimCRL)
pretext_encoder:
  type: MLP
  hidden: [128]
  feature_dim: 48

pretext_optimizer:
  type: NAdam
  lr: 6.18765968088268E-05
  weight_decay: 8.32978722530797E-06
  lr_scheduler: cosine
  lr_scheduler_decay: 0.27129774818549

pretext_transforms:
  gauss_scale: 0.0618487302293532

pretext_clr_loss:
  temperature: 0.13298238260213

pretext_training:
  batch_size: 210
  epochs: 200
