data:
  batch_size: 64
  n_classes: 2

encoder:
  encoder_hidden: [12, 24, 48]
  encoder_dim: 48
  feature_dim: 12

optimizer:
  type: NAdam
  lr: 0.001
  weight_decay: 0.002
  lr_scheduler: cosine
  lr_scheduler_decay: 0.1

clr_loss:
  temperature: 0.1

training:
  epochs: 200
