data:
  batch_size: 64
  n_classes: 10

encoder:
  encoder_hidden: [24, 12]
  encoder_dim: 12
  feature_dim: 12

optimizer:
  type: NAdam
  lr: 0.01
  weight_decay: 0.0
  lr_scheduler: cosine
  lr_scheduler_decay: 0.00001

clr_loss:
  temperature: 0.1

training:
  epochs: 200
